language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libogg-dev
      - libopus-dev
  homebrew:
    brewfile: true

env: PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
